services:
  web:
    build: .
    command: gunicorn hr_rag.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - chroma-data:/app/chroma_db
      - document-data:/app/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  postgres-data:
  chroma-data:
  document-data: